plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.5' apply false
    id 'io.spring.dependency-management' version '1.1.7' apply false
}

group = 'com.sarthak.projects'
version = '0.0.1-SNAPSHOT'

ext {
    jjwtVersion = '0.13.0'
    mapstructVersion = '1.6.3'
    springAiVersion = '2.0.0-M5'
    springCloudVersion = '2025.1.0'
}

allprojects {
    group = rootProject.group
    version = rootProject.version

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'io.spring.dependency-management'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    configurations {
        compileOnly {
            extendsFrom annotationProcessor
        }
    }

    dependencyManagement {
        imports {
            mavenBom org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES
            mavenBom "org.springframework.cloud:spring-cloud-dependencies:${rootProject.ext.springCloudVersion}"
            mavenBom "org.springframework.ai:spring-ai-bom:${rootProject.ext.springAiVersion}"
        }
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }
}

tasks.named('compileJava') {
    enabled = false
}

tasks.named('processResources') {
    enabled = false
}
