services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_DB: testDB
      POSTGRES_USER: testUser
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/18/docker
      TZ: Asia/Kolkata
      PGTZ: Asia/Kolkata
    ports:
      - "9000:5432"
    volumes:
      - D:\ProgramFiles\workspace-spring-tool-suite-4-4.23.1.RELEASE\CodePilotAi\codepilot-ai-db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testUser -d testDB"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  minio:
    image: quay.io/minio/minio:latest
    container_name: codepilot-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9001:9000"
      - "9002:9001"
    volumes:
      - codepilot-minio-data:/data
    restart: unless-stopped

volumes:
  codepilot-minio-data:
